-- Initial schema: leads table.
--
-- RLS is intentionally OFF — inserts arrive only via the server-side API route
-- using the service role key. If you later expose this table to the client
-- (e.g. an admin dashboard signed in with Supabase Auth), enable RLS and add
-- explicit policies in a follow-up migration. Do not edit this file once any
-- production data exists; add a new migration instead.

create extension if not exists "pgcrypto";

create table if not exists public.leads (
    id          uuid          primary key default gen_random_uuid(),
    email       text          not null,
    name        text,
    message     text,
    source      text          not null default 'site',
    created_at  timestamptz   not null default now()
);

-- Case-insensitive uniqueness on email so duplicates from "Foo@bar.com" vs
-- "foo@bar.com" do not pile up. The API route lowercases on write but the
-- index keeps us honest if anyone inserts directly.
create unique index if not exists leads_email_lower_unique
    on public.leads (lower(email));

create index if not exists leads_created_at_idx
    on public.leads (created_at desc);

create index if not exists leads_source_idx
    on public.leads (source);

comment on table public.leads is
    'Inbound lead form submissions. Server-only writes via service role.';

comment on column public.leads.source is
    'Where the lead originated (e.g., "form", "api", "import"). Free-form for v0; promote to enum if values stabilise.';
